# Profile: default
spring:
  application:
    name: CloudQuery
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT:5432}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

openweathermap:
  apikey: ${OPENWEATHERMAP_APIKEY}
---
# Profile: dev
spring:
  config:
    activate:
      on-profile: dev

# During development, Hibernate takes care of migration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
---
# Profile: test
spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create-drop