spring:
  application:
    name: CloudQuery
  data:
    mongodb:
      database: cloud_query
      authentication-database: admin
      host: ${MONGO_HOST}
      port: ${MONGO_PORT:27017}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

openweathermap:
  apikey: ${OPENWEATHERMAP_APIKEY}