spring:
  application:
    name: CloudQuery
  data:
    mongodb:
      database: ${MONGO_DB}
      authentication-database: admin
      host: ${MONGO_HOST}
      port: ${MONGO_PORT:27017}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT:5432}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

openweathermap:
  apikey: ${OPENWEATHERMAP_APIKEY}

logging:
  level:
    com.github.prominence: DEBUG
