services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: cloudquery
      POSTGRES_PASSWORD: FCHigAUt8i3HxNDk
      POSTGRES_DB: cloudquery
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: